name: library_starter
description: Library Starter
author: NobiDev <opensource@nobidev.com>
homepage: https://github.com/NobiDev/native-library-starter

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.2

flutter:
